//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretzel.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Liquid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Liquid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretzel.Logic.Properties.Liquid", typeof(Liquid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout: post
        ///title: About
        ///comments: false
        ///---
        ///
        ///New Site
        ///
        ///##To Do
        ///
        ///Edit this Markdown to add an about page.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout: nil
        ///---
        ///&lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title&gt;Feed Name&lt;/title&gt;
        ///  &lt;link href=&quot;http://domain/&quot;/&gt;
        ///  &lt;link type=&quot;application/atom+xml&quot; rel=&quot;self&quot; href=&quot;http://domain/atom.xml&quot;/&gt;
        ///  &lt;updated&gt;{{ site.time | date_to_xmlschema }}&lt;/updated&gt;
        ///  &lt;id&gt;http://domain/&lt;/id&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Author&lt;/name&gt;
        ///    &lt;email&gt;Email&lt;/email&gt;
        ///  &lt;/author&gt;
        ///
        ///  {% for post in site.posts %}
        ///  &lt;entry&gt;
        ///    &lt;id&gt;http://domain/{{ post.url }}&lt;/id&gt;
        ///    &lt;link type=&quot;text/html&quot; rel=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Atom {
            get {
                return ResourceManager.GetString("Atom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pretzel: 
        ///    engine: liquid.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- 
        ///layout: post
        ///title: &quot;My First Post&quot;
        ///author: &quot;Author&quot;
        ///comments: true
        ///---
        ///
        ///## Hello world...
        ///
        ///```cs
        ///static void Main() 
        ///{
        ///    Console.WriteLine(&quot;Hello World!&quot;);
        ///}
        ///```
        ///
        ///
        ///This is my first post on the site!.
        /// </summary>
        internal static string FirstPost {
            get {
                return ResourceManager.GetString("FirstPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;head&gt;
        ///		&lt;meta content=&quot;en-au&quot; http-equiv=&quot;Content-Language&quot; /&gt;
        ///		&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///		&lt;link href=&quot;/rss.xml&quot; type=&quot;application/rss+xml&quot; rel=&quot;alternate&quot; title=&quot;Blog Feed&quot; /&gt;
        ///		&lt;link href=&quot;/atom.xml&quot; type=&quot;application/atom+xml&quot; rel=&quot;alternate&quot; title=&quot;Blog Feed&quot; /&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1&quot; /&gt;
        ///		&lt;title&gt;{{ page.title }}&lt;/title&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/css/style.css&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout : layout
        ///title : SiteName
        ///---
        ///
        ///&lt;ul class=&quot;posts&quot;&gt;
        ///    {% for post in site.posts  limit:5 %}
        ///		&lt;li&gt;
        ///			&lt;div class=&quot;idea&quot;&gt;
        ///				{% if forloop.first and post.layout == &quot;post&quot; %}
        ///					&lt;h1&gt;&lt;a href=&quot;{{ post.url }}&quot;&gt;{{ post.title }}&lt;/a&gt;&lt;/h1&gt;
        ///					&lt;div class=&quot;postdate&quot;&gt;{{ post.date | date: &quot;%e %B, %Y&quot;  }}
        ///						&lt;ul&gt;
        ///						{% for tag in post.tags %}
        ///							&lt;li&gt;&lt;a href=&quot;/tag/{{ tag }}&quot;&gt;{{ tag }}&lt;/a&gt;&lt;/li&gt;
        ///						{% endfor %}
        ///						&lt;/ul&gt;
        ///					&lt;/div&gt;
        ///					{{ post.content }}
        ///					&lt;br /&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///	{% include head.liquid %}
        ///	&lt;body&gt;
        ///		&lt;div id=&quot;container&quot;&gt;
        ///			&lt;div id=&quot;side&quot;&gt;
        ///				&lt;a href=&quot;/&quot; id=&quot;home&quot; title=&quot;home&quot; alt=&quot;home&quot;&gt;&lt;img src=&quot;/img/logo.png&quot; alt=&quot;Site Name&quot; /&gt;&lt;/a&gt;
        ///				&lt;div id=&quot;hometext&quot;&gt;&lt;a href=&quot;/&quot; &gt;Site Name&lt;/a&gt;&lt;/div&gt;
        ///				&lt;div class=&quot;section&quot;&gt;
        ///					&lt;ul&gt;
        ///						&lt;li&gt;&lt;a href=&quot;/about.html&quot;&gt;about&lt;/a&gt;&lt;/li&gt;
        ///						&lt;li&gt;&lt;a href=&quot;/r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout: layout
        ///---
        ///
        ///&lt;div class=&quot;entry-container&quot;&gt;
        ///	&lt;div class=&apos;entry&apos;&gt;
        ///		&lt;h1&gt; {{page.title}} &lt;/h1&gt;
        ///		&lt;span class=&quot;postdate&quot;&gt;{{ page.date | date: &quot;%e %B, %Y&quot;  }}
        ///			{% for tag in page.tags %}
        ///				&lt;li&gt;&lt;a href=&quot;/tag/{{ tag }}&quot;&gt;{{ tag }}&lt;/a&gt;&lt;/li&gt;
        ///			{% endfor %}
        ///		&lt;/span&gt;
        ///		{{ content }}
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;div id=&quot;page-navigation&quot;&gt; 
        ///	&lt;div class=&quot;left&quot;&gt; {% if page.previous.url %} &lt;a href=&quot;{{page.previous.url}}&quot; title=&quot;Previous Post: {{page.previous.title}}&quot;&gt;&amp;larr; {{page.previous.title}}&lt;/a&gt; {%  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout: nil
        ///---
        ///&lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot; xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///&lt;channel&gt;
        ///    &lt;title&gt;Feed Name&lt;/title&gt;
        ///    &lt;link&gt;http://domain/&lt;/link&gt;
        ///    &lt;atom:link href=&quot;http://domain/rss.xml&quot; rel=&quot;self&quot; type=&quot;application/rss+xml&quot; /&gt;
        ///    &lt;description&gt;&lt;/description&gt;
        ///    &lt;language&gt;en-au&lt;/language&gt;
        ///    &lt;pubDate&gt;{{ site.time | date: &quot;%a, %d %b %Y %H:%M:%S %z&quot; }}&lt;/pubDate&gt;
        ///    &lt;lastBuildDate&gt;{{ site.time | date: &quot;%a, %d %b %Y %H:%M:%S %z&quot; }}&lt;/lastBuildDate&gt;
        ///    {% for post i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout: nil
        ///---
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;urlset
        ///  xmlns=&quot;http://www.sitemaps.org/schemas/sitemap/0.9&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://www.sitemaps.org/schemas/sitemap/0.9
        ///  http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd&quot;&gt;
        ///  &lt;!-- Generated with pretzel --&gt;
        ///  {% for post in site.posts %}
        ///  &lt;url&gt;
        ///    &lt;loc&gt;http://domain{{ post.url }}&lt;/loc&gt;
        ///    &lt;lastmod&gt;{{ post.date | date_to_xmlschema }}&lt;/lastmod&gt;
        ///    &lt;changefreq&gt;dail [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sitemap {
            get {
                return ResourceManager.GetString("Sitemap", resourceCulture);
            }
        }
    }
}
