//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretzel.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RazorAzure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RazorAzure() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretzel.Logic.Properties.RazorAzure", typeof(RazorAzure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???namespace Shim
        ///{
        ///	//Without a CS file in a CSProj, MSBuild will fail throwing CS2008 
        ///    class Shim
        ///    {
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string Shim {
            get {
                return ResourceManager.GetString("Shim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Release&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{08524E18-F666-4F41-93D5-6AB6D97A58E2}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/Out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShimProject {
            get {
                return ResourceManager.GetString("ShimProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???
        ///Microsoft Visual Studio Solution File, Format Version 11.00
        ///# Visual Studio 2010
        ///Project(&quot;{E24C65DC-7377-472B-9ABA-BC803B73C61A}&quot;) = &quot;Sham&quot;, &quot;_source\_site&quot;, &quot;{F74001E8-C911-4A56-A200-7F6B85564035}&quot;
        ///	ProjectSection(WebsiteProperties) = preProject
        ///		TargetFrameworkMoniker = &quot;.NETFramework,Version%3Dv4.0&quot;
        ///		Release.AspNetCompiler.VirtualPath = &quot;/&quot;
        ///		Release.AspNetCompiler.PhysicalPath = &quot;_source\_site&quot;
        ///		Release.AspNetCompiler.TargetPath = &quot;shim&quot;
        ///		Release.AspNetCompiler.Updateable = &quot;true&quot;
        ///		Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShimSolution {
            get {
                return ResourceManager.GetString("ShimSolution", resourceCulture);
            }
        }
    }
}
