//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretzel.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RazorWiki {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RazorWiki() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretzel.Logic.Properties.RazorWiki", typeof(RazorWiki).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///	padding-top: 80px;
        ///	padding-bottom: 40px;
        ///}
        ///.
        /// </summary>
        internal static string DefaultStyle {
            get {
                return ResourceManager.GetString("DefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///layout : layout
        ///title : Wiki Home
        ///---
        ///
        ///## Welcome to your pretzel Wiki
        ///
        ///Simply create folders, and .md files in your pretzel site, and the layout will automatically build a wiki content tree for you
        ///
        ///Use `order: X` in your yaml front matter to order files.
        ///
        ///Each folder should contain an index.md file.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System
        ///@using System.Collections.Generic
        ///@using System.Linq
        ///@using System.Text
        ///@using Pretzel.Logic.Templating.Context
        ///@using Page = Pretzel.Logic.Templating.Context.Page
        ///@inherits RazorEngine.Templating.TemplateBase&lt;PageContext&gt;
        ///@functions {
        ///
        ///    static string WriteOutContents(PageContext context, IEnumerable&lt;Page&gt; pages, string path)
        ///    {
        ///        var level = path.Count(c=&gt;c==&apos;/&apos;);
        ///        var indent = string.Empty.PadLeft(((level - 1) * 4)) + &quot;                        &quot;;
        ///        var sb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.menu-toggle {
        ///    display:run-in !important;
        ///    width=10px !important;
        ///    margin-right:10px !important;
        ///}
        ///
        ///.menu-toggle:hover {
        ///    color: black !important;
        ///}
        ///
        ///.sidebar-nav {
        ///	padding: 9px 0;
        ///}
        ///
        ///.navbar .brand { 
        ///	margin-top: 10px;
        ///	margin-left: 5px;
        ///	color: White;
        ///	text-shadow: none;
        ///}
        ///
        ///.btn-navbar {
        ///	margin-top: 10px;
        ///}
        ///
        ///.navbar-inner {
        ///	background: #394755;
        ///}
        ///
        ///.navbar-link {
        ///	color: white;
        ///	font-size: 16px;
        ///	margin: 10px 0 10px 10px;
        ///	padding-right: 0px;
        ///}
        ///
        ///.navba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
