//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pretzel.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pretzel.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon faviconico {
            get {
                object obj = ResourceManager.GetObject("faviconico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap faviconpng {
            get {
                object obj = ResourceManager.GetObject("faviconpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.3 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.3&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JQuery {
            get {
                return ResourceManager.GetString("JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(){var r=null;
        ///(function(){function X(e){function j(){try{J.doScroll(&quot;left&quot;)}catch(e){P(j,50);return}w(&quot;poll&quot;)}function w(j){if(!(j.type==&quot;readystatechange&quot;&amp;&amp;x.readyState!=&quot;complete&quot;)&amp;&amp;((j.type==&quot;load&quot;?n:x)[z](i+j.type,w,!1),!m&amp;&amp;(m=!0)))e.call(n,j.type||j)}var Y=x.addEventListener,m=!1,C=!0,t=Y?&quot;addEventListener&quot;:&quot;attachEvent&quot;,z=Y?&quot;removeEventListener&quot;:&quot;detachEvent&quot;,i=Y?&quot;&quot;:&quot;on&quot;;if(x.readyState==&quot;complete&quot;)e.call(n,&quot;lazy&quot;);else{if(x.createEventObject&amp;&amp;J.doScroll){try{C=!n.frameElement}catch(A){}C&amp;&amp; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RunPrettify {
            get {
                return ResourceManager.GetString("RunPrettify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body 
        ///{ 
        ///	font-family: Segoe UI, sans-serif; 
        ///	margin-left:auto; 
        ///	margin-right: auto;
        ///	width:1100px; 
        ///}
        ///h1,h2,h3,h4,h5,h6 
        ///{ 
        ///	font-family: Segoe UI Light, Segoe WP Light, Segoe UI, Helvetica, sans-serif; 
        ///	font-weight: lighter; 
        ///	margin-bottom:0px; 
        ///}
        ///h1 
        ///{ 
        ///	font-size: 4em;
        ///}
        ///h2 
        ///{ 
        ///	font-size: 2.5em;
        ///}
        ///a, a:visited 
        ///{ 
        ///	text-decoration: none; 
        ///	color:#13678b;
        ///}
        ///a:hover 
        ///{
        ///	color:white; 
        ///	background: #13678b
        ///}
        ///ul 
        ///{
        ///	margin:0; 
        ///	padding:0;
        ///}
        ///li 
        ///{ 
        ///	margin:0; 
        ///	padd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
    }
}
